(source "gnu" "http://elpa.gnu.org/packages/")
(source "org" "http://orgmode.org/elpa/")
(source "melpa" "http://melpa.milkbox.net/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(depends-on "auto-complete")
(depends-on "csharp-mode")
(depends-on "evil")
(depends-on "evil-leader")
(depends-on "evil-nerd-commenter")
(depends-on "evil-numbers")
(depends-on "evil-paredit")
(depends-on "flymake")
(depends-on "flymake-easy")
(depends-on "flymake-php")
(depends-on "flymake-phpcs")
(depends-on "git-gutter-fringe")
(depends-on "glsl-mode")
(depends-on "go-mode")
(depends-on "haskell-mode")
(depends-on "less-css-mode")
(depends-on "markdown-mode")
(depends-on "org")
(depends-on "paredit")
(depends-on "php-mode")
(depends-on "popup")
(depends-on "powerline")
(depends-on "rainbow-delimiters")
(depends-on "rust-mode")
(depends-on "smart-mode-line")
(depends-on "tuareg")
(depends-on "undo-tree")
(depends-on "yasnippet")

(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "expand-region")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "popwin")
(depends-on "projectile")
(depends-on "s")
(depends-on "smex")
(depends-on "wrap-region")

(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "gandalf-theme")
