(load "~/.emacs.d/setup.el")
(load "~/.emacs.d/behavior.el")
(load "~/.emacs.d/appearance.el")
(load "~/.emacs.d/font-and-theme.el")
(load "~/.emacs.d/orgmode.el")
(load "~/.emacs.d/powerline.el")
(load "~/.emacs.d/hooks.el")
