(require 'cask "~/.cask/cask.el")
(cask-initialize)

(require 'auto-complete)
(require 'auto-complete-config)
(require 'auto-complete-clang)
(require 'cl)
(require 'ido)
(require 'org)
(require 'package)
(require 'powerline)

(require 'uniquify)
(require 'whitespace)
(require 'yasnippet)
